# Generated by Django 4.2.7 on 2026-03-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(db_index=True, max_length=50, verbose_name='监测点编号')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('time', models.TimeField(db_index=True, verbose_name='时间')),
                ('chlorine', models.FloatField(verbose_name='余氯(mg/L)')),
                ('conductivity', models.FloatField(verbose_name='电导率(µS/cm)')),
                ('ph', models.FloatField(verbose_name='pH值')),
                ('orp', models.FloatField(verbose_name='氧化还原电位(mV)')),
                ('turbidity', models.FloatField(verbose_name='浊度(NTU)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '水质记录',
                'verbose_name_plural': '水质记录',
                'db_table': 'api_waterqualityrecord',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['point_id'], name='api_waterqu_point_i_44a2b7_idx'), models.Index(fields=['date'], name='api_waterqu_date_7f3b9e_idx'), models.Index(fields=['point_id', 'date'], name='api_waterqu_point_i_7f3e1b_idx')],
            },
        ),
    ]
