# Generated by Django 6.0.3 on 2026-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='监测点编号')),
                ('name', models.CharField(max_length=100, verbose_name='监测点名称')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='经度')),
                ('location_description', models.TextField(blank=True, null=True, verbose_name='位置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监测点',
                'verbose_name_plural': '监测点',
                'db_table': 'api_monitoringpoint',
                'ordering': ['point_id'],
            },
        ),
    ]
